(function(){
    //页面初始化
    window.onload = function(){

    };
    function paging(){
        var products = new Vue({
            el:"#products",
            data:{
                list:[
                    {
                        name:"FireFlex",
                        type:"水冷",
                        size:[
                            "75x10",
                            "80x10",
                            "110x10",
                            "120x10"
                        ],
                        length:1
                    },
                    {
                        name:"FireEdge",
                        type:"风冷",
                        size:[
                            "75x10",
                            "80x10",
                            "110x10",
                            "120x10"
                        ],
                        length:2
                    },
                    {
                        name:"FireEdge",
                        type:"风冷",
                        size:[
                            "75x10",
                            "80x10",
                            "110x10",
                            "120x10",
                            "80x10",
                            "110x10",
                            "120x10"
                        ],
                        length:3
                    },{
                        name:"FireFlex",
                        type:"水冷",
                        size:[
                            "75x10",
                            "80x10",
                            "110x10",
                            "120x10"
                        ],
                        length:4
                    },
                    {
                        name:"FireEdge",
                        type:"风冷",
                        size:[
                            "75x10",
                            "80x10",
                            "110x10",
                            "120x10"
                        ],
                        length:5
                    },
                    {
                        name:"FireEdge",
                        type:"风冷",
                        size:[
                            "75x10",
                            "80x10",
                            "110x10",
                            "120x10",
                            "80x10",
                            "110x10",
                            "120x10"
                        ],
                        length:6
                    },{
                        name:"FireFlex",
                        type:"水冷",
                        size:[
                            "75x10",
                            "80x10",
                            "110x10",
                            "120x10"
                        ],
                        length:7
                    },
                    {
                        name:"FireEdge",
                        type:"风冷",
                        size:[
                            "75x10",
                            "80x10",
                            "110x10",
                            "120x10"
                        ],
                        length:8
                    },
                    {
                        name:"FireEdge",
                        type:"风冷",
                        size:[
                            "75x10",
                            "80x10",
                            "110x10",
                            "120x10",
                            "80x10",
                            "110x10",
                            "120x10"
                        ],
                        length:9
                    }
                ]
            },
            methods:{
                showMenu:function(){
                    var e = event.target;
                    if($(e).next().css("display")=='none'){
                        $(".secondMenu").css("display","none");
                        $(e).next().css("display","block");
                    }else{
                        $(".secondMenu").css("display","none");
                        $(e).next().css("display","none");
                    }
                }
            }
        })
    }
    function bindLabelEventInit(){

    }
    function onEnter () {
        bindLabelEventInit ();
        paging ();
    }
    onEnter();
})();